1. What is the output of the following code?
nums = set([1,1,2,3,3,3,4,4])
print(len(nums))

In [2]:
nums = set([1,1,2,3,3,3,4,4])
print(nums)
print(len(nums))

{1, 2, 3, 4}
4

2. What will be the output? d = {"john":40, "peter":45} print(list(d.keys()))

In [3]:
d = {"john":40, "peter":45}
print(list(d.keys()))
print((d.keys()))

['john', 'peter']
dict_keys(['john', 'peter'])

3. A website requires a user to input username and password to register. Write a program to check the validity of password given by user. Following are the criteria for checking password:

a) At least 1 letter between [a-z]

b) At least 1 number between [0-9]

c) At least 1 letter between [A-Z]

d) At least 1 character from [$#@]

e) Minimum length of transaction password: 6

f) Maximum length of transaction password: 12

In [6]:
import re

def is_valid_password(password):
    if len(password)<6 or len(password)<12:
        return False

    if not re.search(r"[a-z]",password):
        return False

    if not re.search(r"[A-Z]", password):
        return False

    if not re.search(r"0-9", password):
        return False

    if not re.search(r"[$#@]", password):
        return False

    else:
        return True

passwords = input("Enter a password: ").split(",")
for pwd in passwords:
    if is_valid_password(pwd):
        print(f"'{pwd}' is a valid password.")
    else:
        print(f"'{pwd}' is an invalid password.")

Enter a password: Pass@13
'Pass@13' is an invalid password.

4. Write a for loop that prints all elements of a list and their position in the list.

In [7]:
a = [4,7,3,2,5,9]

for index, value in enumerate(a):
 print (f"elements at position {index} is {value}")

elements at position 0 is 4
elements at position 1 is 7
elements at position 2 is 3
elements at position 3 is 2
elements at position 4 is 5
elements at position 5 is 9

5. Please write a program which accepts a string from console and print the characters that have even indexes.

Example: If the following string is given as input to the program: H1e2l3l4o5w6o7r8l9d

Then, the output of the program should be: Helloworld

In [12]:
user_input = input("Enter a input:")

even_index_characters = user_input[::2]
print(even_index_characters)

Enter a input:H1e2l3l4o5w6o7r8l9d
Helloworld

6. Please write a program which accepts a string from console and print it in reverse order.

In [13]:
input_string = input("Enter a string: ")
reversed_string = input_string[::-1]
print("Reversed string:", reversed_string)

Enter a string: string
Reversed string: gnirts

7. Please write a program which count and print the numbers of each character in a string input by console.

In [14]:
input_string  = "abcdefgabc"

char_count = {}

for char in input_string:
    if char in char_count:
        char_count[char]+=1
    else:
        char_count[char] = 1

for char,count in char_count.items():
    print(f"the'{char}'have the count of '{count}'")

the'a'have the count of '2'
the'b'have the count of '2'
the'c'have the count of '2'
the'd'have the count of '1'
the'e'have the count of '1'
the'f'have the count of '1'
the'g'have the count of '1'

8. With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists

In [15]:
a= [1,3,6,78,35,55]
b = [12,24,35,24,88,120,155]
intersecion = list(set(a)& set(b))
print(intersecion)

[35]

9. With a given list [12,24,35,24,88,120,155,88,120,155], write a program to print this list after removing all duplicate values with original order reserved.

In [16]:
list = [12,24,35,24,88,120,155,88,120,155]
l = set(list)
sorted_list = sorted(l)
print(sorted_list)

[12, 24, 35, 88, 120, 155]

10. By using list comprehension, please write a program to print the list after removing the value 24 in [12,24,35,24,88,120,155].

In [17]:
list1 = [12,24,35,24,88,120,155]
l = [i for i in list1 if i!=24]
print(l)

[12, 35, 88, 120, 155]

11. By using list comprehension, please write a program to print the list after removing the 0th,4th,5th numbers in [12,24,35,70,88,120,155]

In [19]:
a = [12,24,35,70,88,120,155]
output = [item for index , item in enumerate(a) if index not in(0,4,5)]

print(output)

[24, 35, 70, 155]

12. . By using list comprehension, please write a program to print the list after removing delete numbers which are divisible by 5 and 7 in [12,24,35,70,88,120,155].

In [20]:
input = [12,24,35,70,88,120,155]

output = [i for i in input if not (i%5==0 and i%7==0)]

print(output)

[12, 24, 88, 120, 155]

13. Please write a program to randomly generate a list with 5 numbers, which are divisible by 5 and 7 , between 1 and 1000 inclusive.

In [21]:
import random
num = [i for i in range(1,1001) if (i%5==0 and i%7==0)]
random_num = random.sample(num,5)

print(random_num)

[280, 805, 245, 595, 910]

14. Write a program to compute 1/2+2/3+3/4+...+n/n+1 with a given n input by console (n>0).
Example: If the following n is given as input to the program: 5

Then, the output of the program should be: 3.55

In [22]:
n = 2


if n <= 0:
    print("n must be greater than 0")
else:

    total = sum(i / (i + 1) for i in range(1, n + 1))

    print(f"The result is: {total:.2f}")

The result is: 1.17